# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: myapp-app
    container_name: myapp-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html  # Mount whole project
      - vendor:/var/www/html/vendor # Except vendor
      - composer_cache:/composer/cache
    environment:
      - COMPOSER_CACHE_DIR=/composer/cache
      - APP_ENV=${APP_ENV}
      - APP_ENV_FILE=.env.${APP_ENV}
    depends_on:
      - mysql
      # - postgres
      - redis
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: myapp-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # postgres:
  #   image: postgres:15
  #   container_name: myapp-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - laravel

  mysql:
    image: mysql:5.7
    container_name: myapp-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: myapp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  # soketi:
  #   image: quay.io/soketi/soketi:latest
  #   container_name: soketi-server
  #   restart: unless-stopped
  #   environment:
  #     SOKETI_DEBUG: '1'
  #     SOKETI_METRICS_SERVER_PORT: '9601'
  #     SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID}
  #     SOKETI_DEFAULT_APP_KEY: ${PUSHER_APP_KEY}
  #     SOKETI_DEFAULT_APP_SECRET: ${PUSHER_APP_SECRET}
  #     SOKETI_DEFAULT_APP_ENABLED: 'true'
  #   ports:
  #     - '6001:6001'
  #     - '9601:9601'
  #   networks:
  #     - laravel

  # queue:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: myapp-queue
  #   command: php artisan queue:work --sleep=3 --tries=3
  #   depends_on:
  #     - redis
  #     - app
  #   networks:
  #     - laravel

volumes:
  dbdata:
  pgdata:
  vendor:
  composer_cache:

networks:
  laravel:
    driver: bridge
